// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // Main sidebar for the docs pages
    tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],


};
export default sidebars;
